remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: CreateAv7Database
description: [Your Repository Description]

navbar-links:
  Home: /
  Google: https://google.com
  Custom Tab 2: /custom-tab-2
